// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPNaEY0StE8HtTZ32muYX5jkiwlSPLJ4g',
    appId: '1:141638089524:web:e2afd8d310f5c814390361',
    messagingSenderId: '141638089524',
    projectId: 'meetapp-3aec2',
    authDomain: 'meetapp-3aec2.firebaseapp.com',
    storageBucket: 'meetapp-3aec2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFhVAXY0HMTASe14JjOqXU62aUvUt5r7Q',
    appId: '1:141638089524:android:6124f017d4544c29390361',
    messagingSenderId: '141638089524',
    projectId: 'meetapp-3aec2',
    storageBucket: 'meetapp-3aec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBvNxjtIV2i-vDe4nesr7q5yRTYD8EdQQ',
    appId: '1:141638089524:ios:c81bb872f4faf266390361',
    messagingSenderId: '141638089524',
    projectId: 'meetapp-3aec2',
    storageBucket: 'meetapp-3aec2.appspot.com',
    iosBundleId: 'com.example.funFiles',
  );
}
